GET  http://localhost:3000/

### signing up a user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "stroz",
    "email": "stroz@gmail.com",
    "password": "password1234"
}

### logging in
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{ 
       "email": "ITGUY@gmail.com",
    "password": "password1234"
}

### accessing a protected route without a token
post http://localhost:3000/auth/login
Content-Type: application/json

{ 
    "email": "boy@gmail.com",
    "password": "password1234"
}

### accessing a protected route with a token
post http://localhost:3000/api/projects/693735a2900253e8fb24c415/members
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjhjNGVlOGQ4OThhN2Q1ODYxZDE4NyIsImlhdCI6MTc2NTEzOTQ0MywiZXhwIjoxNzY3NzMxNDQzfQ.9v4rGeKjfSlu-H8kDatXLvsLi6A58hE32hkDdM5arkw

{
  "userId": "69349ab3cc3d7184c3bbd77d"
}


### Search for a user to add to a project
GET http://localhost:3000/api/taskshesed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjhjNDQzOGQ4OThhN2Q1ODYxZDE4MyIsImlhdCI6MTc2NTA1OTY4MCwiZXhwIjoxNzY3NjUxNjgwfQ.HZz4yd1rOgk4z3g0jSa_shKdHciGARFTmCt-PA4wAXc
