GET  http://localhost:3000/

### signing up a user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "stroz",
    "email": "stroz@gmail.com",
    "password": "password1234"
}

### logging in
POST http://localhost:3000/auth/login
Content-Type: application/json

{ 
       "email": "ITGUY@gmail.com",
    "password": "password1234"
}

### accessing a protected route without a token
GET http://localhost:3000/auth/me
Content-Type: application/json

{ 
    "email": "boy@gmail.com",
    "password": "password1234"
}

### accessing a protected route with a token
DELETE http://localhost:3000/projects/692d9c3515603f0c98054988/members/69349ab3cc3d7184c3bbd77d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjhjNDQzOGQ4OThhN2Q1ODYxZDE4MyIsImlhdCI6MTc2NTA1OTY4MCwiZXhwIjoxNzY3NjUxNjgwfQ.HZz4yd1rOgk4z3g0jSa_shKdHciGARFTmCt-PA4wAXc

{ 
    "userId": "69349ab3cc3d7184c3bbd77d"  
}

### Search for a user to add to a project
GET http://localhost:3000/users/ME
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjhjNDQzOGQ4OThhN2Q1ODYxZDE4MyIsImlhdCI6MTc2NTA1OTY4MCwiZXhwIjoxNzY3NjUxNjgwfQ.HZz4yd1rOgk4z3g0jSa_shKdHciGARFTmCt-PA4wAXc
